class AppStrings {
  static const users = 'Users';

  static const dummtText = '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Auctor neque vitae tempus quam pellentesque nec nam aliquam. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Convallis aenean et tortor at risus viverra adipiscing. Egestas quis ipsum suspendisse ultrices gravida. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Magnis dis parturient montes nascetur. Lobortis elementum nibh tellus molestie nunc non blandit. Urna condimentum mattis pellentesque id nibh. Odio pellentesque diam volutpat commodo sed. Malesuada proin libero nunc consequat interdum varius sit. Cursus vitae congue mauris rhoncus aenean vel elit. Vitae auctor eu augue ut lectus arcu bibendum at. Congue nisi vitae suscipit tellus.

Interdum varius sit amet mattis. Id nibh tortor id aliquet lectus proin. Ipsum dolor sit amet consectetur adipiscing. Eu augue ut lectus arcu bibendum at varius vel. Eu augue ut lectus arcu bibendum at varius. Eget mi proin sed libero enim sed faucibus. Ac ut consequat semper viverra. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Viverra nam libero justo laoreet sit amet cursus sit. Eget velit aliquet sagittis id consectetur purus ut faucibus. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Sit amet facilisis magna etiam tempor. Morbi leo urna molestie at. Nunc sed blandit libero volutpat sed cras ornare arcu. Cursus metus aliquam eleifend mi. In ante metus dictum at tempor commodo ullamcorper a. Laoreet non curabitur gravida arcu ac tortor.

Ullamcorper eget nulla facilisi etiam dignissim diam quis. Dictum fusce ut placerat orci nulla pellentesque. Facilisis gravida neque convallis a cras semper auctor. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Consectetur adipiscing elit pellentesque habitant morbi tristique. Metus aliquam eleifend mi in nulla posuere. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Sodales ut eu sem integer vitae justo eget. Cursus vitae congue mauris rhoncus aenean. Sapien et ligula ullamcorper malesuada proin libero. Porta nibh venenatis cras sed felis. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Mauris in aliquam sem fringilla ut morbi. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Sed euismod nisi porta lorem mollis aliquam ut porttitor. Fames ac turpis egestas maecenas pharetra. Sapien eget mi proin sed.

Semper quis lectus nulla at volutpat diam ut venenatis tellus. Enim nulla aliquet porttitor lacus luctus. Nisl tincidunt eget nullam non. Est ante in nibh mauris. Tellus in hac habitasse platea dictumst vestibulum. Imperdiet proin fermentum leo vel orci porta non pulvinar. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus et. Sed vulputate odio ut enim blandit. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Amet luctus venenatis lectus magna fringilla. Non diam phasellus vestibulum lorem. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Auctor eu augue ut lectus. Diam in arcu cursus euismod. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Enim neque volutpat ac tincidunt vitae semper quis. Sed faucibus turpis in eu mi. Sagittis nisl rhoncus mattis rhoncus.

Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Amet aliquam id diam maecenas. Ornare arcu odio ut sem nulla pharetra diam sit. Nibh praesent tristique magna sit amet purus. Tincidunt ornare massa eget egestas. Duis tristique sollicitudin nibh sit amet commodo. Ac turpis egestas integer eget aliquet nibh praesent. Risus pretium quam vulputate dignissim suspendisse in est ante. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Tortor consequat id porta nibh venenatis. Mattis nunc sed blandit libero. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Risus sed vulputate odio ut enim. Enim eu turpis egestas pretium.
''';
}
